// todo-app-react/src/components/TodoItem.tsx
import React from "react";
import { Todo } from "../types/todo";

type Props = {
  todo: Todo;
  onToggle: (id: number) => void;
};

const TodoItem = ({ todo, onToggle }: Props) => (
  <li className="flex justify-between items-center p-2 border-b">
    <span
      onClick={() => onToggle(todo.id)}
      className={
        todo.completed
          ? "line-through text-gray-400 cursor-pointer w-full"
          : "cursor-pointer w-full"
      }
    >
      {todo.text}
    </span>
  </li>
);

export default TodoItem;

// todo-app-vue/src/components/TodoItem.vue
<script setup lang="ts">
import type { Todo } from "../types/todo";

defineProps<{ todo: Todo }>();
const emit = defineEmits(["toggle"]);
</script>

<template>
  <li class="flex justify-between items-center p-2 border-b">
    <span
      @click="emit('toggle')"
      :class="
        todo.completed
          ? 'line-through text-gray-400 cursor-pointer w-full'
          : 'cursor-pointer w-full'
      "
    >
      {{ todo.text }}
    </span>
  </li>
</template>
