// todo-app-vue/src/pages/TodoList/index.vue
<script setup lang="ts">
import { useTodoStore } from "../../stores/todo";
import TodoItem from "../../components/TodoItem.vue";
import TodoStats from "../../components/TodoStats.vue";
import TodoEmptyNotice from "../../components/TodoEmptyNotice.vue";

const { todos, toggleTodo } = useTodoStore();
</script>

<template>
  <div class="max-w-xl mx-auto mt-10">
    <h1 class="text-2xl font-bold mb-4 text-center">Vue Todo List</h1>
    <ul>
      <TodoItem
        v-for="todo in todos"
        :key="todo.id"
        :todo="todo"
        @toggle="toggleTodo(todo.id)"
      />
    </ul>
    <router-link
      to="/add"
      className="mt-6 inline-block text-blue-500 hover:underline"
    >
      ➕ 添加任务
    </router-link>
    <TodoStats />
    <TodoEmptyNotice />
  </div>
</template>

// todo-app-react/src/pages/TodoList/index.tsx
import React from "react";
import { Link } from "react-router-dom";
import { useSelector, useDispatch } from "react-redux";
import { RootState } from "../../store";
import { toggleTodo } from "../../store/todoSlice";

import TodoItem from "../../components/TodoItem";
import TodoStats from "../../components/TodoStats";
import TodoEmptyNotice from "../../components/TodoEmptyNotice";

function TodoList() {
  const todos = useSelector((state: RootState) => state.todos.todos);
  const dispatch = useDispatch();

  const handleToggle = (id: number) => {
    dispatch(toggleTodo(id));
  };

  return (
    <div className="max-w-xl mx-auto mt-10">
      <h1 className="text-2xl font-bold mb-4 text-center">React Todo List</h1>
      <ul>
        {todos.map((todo) => (
          <TodoItem key={todo.id} todo={todo} onToggle={handleToggle} />
        ))}
      </ul>
      <Link
        to="/add"
        className="mt-6 inline-block text-blue-500 hover:underline"
      >
        ➕ 添加任务
      </Link>
      <TodoStats />
      <TodoEmptyNotice />
    </div>
  );
}

export default TodoList;
